### ISSUE TITLE
Exception when returning String.Empty in the GetCC() and GetBCC()

### ISSUE THREAD

**Issue by jjcolumb** [egarim/Ultra#1]
**XAF Version**
18.2.4.0

**Platform**
Windows
**Describe the bug**
Exception when returning String.Empty in the GetCC() and GetBCC(). 

From the log:
The parameter 'addresses' cannot be an empty string.

**To Reproduce**
1. Implement interface IBoToEmail
2. Return String.Empty in the GetCC() and GetBCC().
3. SendEmail

**Screenshots**

**XAF Windows **
 - OS: [e.g. Windows 10 ]

**Database **
 - Name: [e.g. SQL Server]

**Comment by egarim** [comment]
This bug is already fixed, you can see the fix here [Fix](https://github.com/egarim/Ultra/blob/master/Ultra.Email/BusinessObjects/SmtpEmailAccount.cs) line 182 to 187. 

this fix will be included in the next version x.x.x.4
